{% set name = "lsst-sphgeom" %}
{% set version = "27.2024.4300" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 25dfb16d2eb480493cdf1b897a132ad5af6419ee8d912da27cefba6d8035aa5e

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env: PYTHONUTF8=1
  number: 0
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - lsst-versions >=1.3.0
    - wheel
    - pybind11 >=2.5.0
    - numpy
    - pip
  run:
    - python
    - hpgeom >=0.8.0

test:
  imports:
    - lsst.sphgeom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lsst/sphgeom
  summary: A spherical geometry library.
  license: BSD-3-Clause AND GPL-3.0-only
  license_file:
    - LICENSE
    - bsd_license.txt
    - gpl-v3.0.txt

extra:
  recipe-maintainers:
    - erykoff
    - timj
    - TallJimbo
    - camposandro
    - roceb
    - mwittgen
