{% set name = "lsst-sphgeom" %}
{% set version = "26.2024.600" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lsst-sphgeom-{{ version }}.tar.gz
  sha256: eac2bd07b4d192da1d3f1ac541baa024b17c426db5e445ed5adb8493c2086fe5

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env: PYTHONUTF8=1
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - lsst-versions >=1.3.0
    - wheel
    - pybind11 >=2.5.0
    - numpy
    - pip
  run:
    - python
    - hpgeom >=0.8.0

test:
  imports:
    - lsst.sphgeom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lsst/sphgeom
  summary: A spherical geometry library.
  license: BSD-3-Clause AND GPL-3.0-only
  license_file:
    - LICENSE
    - bsd_license.txt
    - gpl-v3.0.txt

extra:
  recipe-maintainers:
    - erykoff
    - timj
    - TallJimbo
    - camposandro
