{% set name = "lsst-sphgeom" %}
{% set version = "26.2024.400" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lsst-sphgeom-{{ version }}.tar.gz
  sha256: da5f5d41fc91bcf487b346fb16fb6ddd8668f62e5a9706c7df2f024f040a7a12

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env: PYTHONUTF8=1
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - lsst-versions >=1.3.0
    - wheel
    - pybind11 >=2.5.0
    - numpy
    - pip
  run:
    - python
    - hpgeom >=0.8.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - lsst.sphgeom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lsst/sphgeom
  summary: A spherical geometry library.
  license: BSD-3-Clause AND GPL-3.0-only
  license_file:
    - LICENSE
    - bsd_license.txt
    - gpl-v3.0.txt

extra:
  recipe-maintainers:
    - erykoff
    - timj
    - TallJimbo
    - camposandro
