{% set name = "lsst-sphgeom" %}
{% set version = "29.2025.3502" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 18260b7164daba42ecaf926c2f2c05259ca18e3c11fce8e7e35794b41fa9b264

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env: PYTHONUTF8=1
  number: 0
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - lsst-versions >=1.3.0
    - wheel
    - pybind11 >=3.0.0
    - numpy
    - pip
  run:
    - python
    - hpgeom >=0.8.0

test:
  imports:
    - lsst.sphgeom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lsst/sphgeom
  summary: A spherical geometry library.
  license: BSD-3-Clause AND GPL-3.0-only
  license_file:
    - LICENSE
    - bsd_license.txt
    - gpl-v3.0.txt

extra:
  recipe-maintainers:
    - erykoff
    - timj
    - TallJimbo
    - camposandro
    - roceb
    - mwittgen
